### PR TITLE
Add is_finite method to vectors and matrices.

### PR DESCRIPTION
**Pull request by derekdreery**
This method is useful in debug to error early when some kind of singularity is encountered.

### CODE REVIEW

**Comment by brendanzab** [comment]
Nice! Wonder if we could add this to the `Array` trait? I can accept this as-is though!

**Comment by derekdreery** [comment]
I'll add Array, no worries! Would you like it added to anything else?

**Comment by derekdreery** [comment]
I think it's difficult to add to Array, because it only makes sense on types that are `BaseFloat`. Do you agree?

**Comment by brendanzab** [comment]
You can do `where Self::Element: BaseFloat` - one of the reasons I ask is that `Quaternion` is missing here - theis would have been picked up if it were on the trait.

**Comment by derekdreery** [comment]
Slightly off-topic, but in Array you have swap_elements: how do you know that i and j are in bounds?

**Comment by brendanzab** [comment]
I think that would just panic with an index out of bounds error. We should probably have tests for that though 😅

**Pull request merged**
