### PR TITLE
Added project_on to InnerSpace

### PR DESCRIPTION
**Pull request by DataAnalysisCosby**
Adds a project method to InnerSpace.
IMPORTANT NOTE: I did not check to see if this compiles because I am a bad person :(
I thought I should ask before doing that, should a test be added for this? The correctness of this method somewhat relies on dot and magnitude2 being correct.

### CODE REVIEW

**Comment by brendanzab** [comment]
I think it would be nice to have some tests. Alas, I have also been bad in adding tests to cgmath, and there are various ways that I have implemented them in the library. Could you have a go at adding them anyway?

**Comment by brendanzab** [comment]
Sorry for the late reply - got back from holidays this week and have been fighting jet lag!

**Comment by DataAnalysisCosby** [comment]
Sure, I'll add a few tests when I have some time. And no problem with the late reply, I'm not waiting on this to go through or anything like that. Just thought it would be a useful method.

**Comment by DataAnalysisCosby** [comment]
Hey brendan, just managed to subdue my laziness and add some tests. Hope they work for you!

**Comment by brendanzab** [comment]
Thanks! ❤️

**Pull request merged**
