### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by brendanzab**

### CODE REVIEW

**Comment by mhintz** [comment]
By the way, apologies for not being an active contributor the last few months. I've been dragged back into C++ land for the time being :/

**Comment by mhintz** [comment]
Is there a list of features/bugs you want to complete in order to declare a 1.0 release? Is 1.0 on the horizon, or is it something you'd rather not do?

**Comment by brendanzab** [comment]
Need to clean up the transform API mainly. I was running into type checking problems :( Will have to publish a WIP branch at some stage.

**Comment by brendanzab** [comment]
We also need tons more tests :(

**Pull request merged**
